# Generated by Django 4.1.3 on 2023-02-20 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, unique=True, verbose_name='Название')),
                ('content', models.TextField(help_text='Какая либо подсказка, если имеет смысл', verbose_name='Описание')),
                ('priority', models.IntegerField(default=1, verbose_name='Приоритет сортировки')),
                ('done', models.DateTimeField(blank=True, null=True, verbose_name='Выполнено')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Дело',
                'verbose_name_plural': 'Список дел',
            },
        ),
    ]
