# Generated by Django 4.1.3 on 2022-11-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Имя'),
        ),
    ]
