# Generated by Django 4.1.3 on 2022-11-30 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_person_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'Заказчики'},
        ),
    ]
