# Generated by Django 4.1.3 on 2022-12-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_todolist_options_remove_todolist_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='content',
            field=models.TextField(blank=True, verbose_name='Задачи'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2022-12-08', verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2022-12-08', verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Имя'),
        ),
    ]
