# Generated by Django 4.1.3 on 2022-12-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_todolist_created_alter_todolist_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Общая задача', max_length=255, verbose_name='Имя')),
                ('content', models.TextField(help_text='Какая либо подсказка, если имеет смысл', verbose_name='Задача')),
                ('priority', models.IntegerField(default=1, verbose_name='Приоритет сортировки')),
                ('done', models.DateTimeField(blank=True, null=True, verbose_name='Выполнено')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Журнал',
                'ordering': ('priority', 'created'),
            },
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2022-12-20', verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2022-12-20', verbose_name='Дата завершения'),
        ),
    ]
