# Generated by Django 4.1.3 on 2022-12-28 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_alter_todolist_created_alter_todolist_due_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('priority', 'created'), 'verbose_name': 'Дела', 'verbose_name_plural': 'Список дел'},
        ),
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='content',
            field=models.TextField(help_text='Какая либо подсказка, если имеет смысл', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
